swagger: '2.0'
info:
  description: This API is a way to implement Google Search Engine into GAE Flexible
  version: 1.0.1
  title: Internet of Things Analytical Ecosystem Search Internal API
  contact: {}
host: 'localhost:8080'
basePath: /
schemes:
  - http
paths:
  '/algorithms/{algorithmID}':
    get:
      tags:
        - Algorithms
      summary: Single Algorithm data
      description: >-
        The Algorithm Details endpoint returns detailed description of a given
        algorithm.
      operationId: AlgorithmsIdHandler.get
      consumes: []
      produces:
        - application/json
      parameters:
        - name: algorithmID
          in: path
          description: ID of an algorithm
          required: true
          type: string
      responses:
        '200':
          description: Details of the algorithm
          schema:
            $ref: '#/definitions/Algorithms'
        '404':
          description: The given algorithmID was not found in collection
  /:
    get:
      tags:
        - Algorithms
      summary: >-
        The Algorithms endpoint returns information about the available
        algorithms.
      description: >-
        The Algorithms endpoint returns information about the available
        algorithms. The response includes the display name and other details
        about each algorithm. It also allows full-text search of tags.
      operationId: AlgorithmsHandler.get
      consumes: []
      produces:
        - application/json
      parameters:
        - name: tags
          in: query
          description: Comma separated Tags for search query.
          required: false
          type: string
          x-example: 'sum two items, sum multiple items'
      responses:
        '200':
          description: An array of algorithms
          schema:
            type: array
            items:
              $ref: '#/definitions/Algorithms'
    post:
      tags:
        - Algorithms
      summary: Add a new Algorithm
      description: Add a new Algorithm
      operationId: AlgorithmsHandler.post
      consumes:
        - application/json
      produces: []
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Algorithms'
      responses:
        '200':
          description: OK
        '400':
          description: Malformed data
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: No authentication. Need to login.
        '403':
          description: Not authorized to post new algorithms
        '409':
          description: AlgorithmID already exists.
          schema:
            $ref: '#/definitions/Error'
definitions:
  Algorithms:
    type: object
    properties:
      algorithmId:
        type: string
        description: Unique identifier representing a specific algorithm.
      algorithmSummary:
        type: string
        description: Brief summary of the algorithm.
      displayName:
        type: string
        description: Display name of the algorithm.
      linkURL:
        type: string
        description: detailed url of the algorithm.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      fields:
        type: string
      message:
        type: string
